### ISSUE TITLE
Multiple source file extensions

### ISSUE THREAD

**Issue by avdstaaij** [avdstaaij/cpp-init#1]
We should support using multiple source file extensions at once, such as `.cpp` and `.cc`.
The user should be able to specify multiple extensions explicitly, or to specify a pattern for source file extensions or filenames.

For example:
`SRCEXT = .cpp .cc`
or:
`SRCPAT = "*.cpp|*.cc"`

**Comment by Thyrum** [comment]
The exact same problem is mentioned [here](https://stackoverflow.com/questions/8969015/working-with-multiple-source-file-extensions-in-a-makefile) on stackoverflow. The easy solution would require GNU make 3.81 or newer.

**Comment by Thyrum** [comment]
I'm having second thoughts on adding this. It obscures the code a lot and doesn't add a lot of functionality. When does your project use 2 different source extensions anyway? The only case I know of is a mixed C/C++ project but in that case, custom compilation rules should be defined for the C files anyway.

**Comment by avdstaaij** [comment]
I suppose that this is mostly a problem with the implementation used in #4.
There wouldn't be a problem if it was just a one-line change, though that's probably not possible.

I agree that the complication of the code may not be worth the added functionality and I'm fine with closing #4, even though I don't think it is entirely without merit.

This feature is indeed so niche that I'm also fine with closing this issue. I recommend labelling it as wontfix in that case.

**Comment by Thyrum** [comment]
Closing this since the code complication (as currently implemented on #4) is not worth the added functionality. Feel free to reopen this when a simpler implementation is thought of.

Not labelling this as a wontfix since if possible (and simple enough), this will be fixed.
