### ISSUE TITLE
Reduce intrusiveness of make clean

### ISSUE THREAD

**Issue by avdstaaij** [avdstaaij/cpp-init#3]
`make clean` currently removes all empty directories recursively. This is far too intrusive. It can even break git repositories by deleting directories inside `.git`, causing `git` to longer recognize the repository (this can usually be repaired with `git init`).
We should only clean the temporary directories that were created by the Makefile.

**Comment by avdstaaij** [comment]
Possible implementation:
Iterate through the directories of `{OBJ|DEP}DIR_{R|D}` from right to left and remove empty directories only along those paths.

**Comment by Thyrum** [comment]
I'd propose using something like
```bash
rm $(OBJS_R) $(OBJS_D) $(DEPS)
rmdir -p $(dir $(OBJS_R))
rmdir -p $(dir $(OBJS_D))
rmdir -p $(dir $(DEPS))
```

This should also work in comibnation with #2. One drawback is however that whenever an object file gets obsolete (because the corresponding source file is deleted) it never gets deleted and prevents properly cleaning because `rmdir` won't work anymore. Thus this requires a bit more thought.

**Comment by Thyrum** [comment]
On second thought, we should probably use
```bash
rm $(BIN_R) $(BIN_D)
find $(OBJDIR) -type f -name '*.o'  -delete 2>/dev/null
find $(DEPDIR) -type f -name '*.d'  -delete 2>/dev/null
find $(DEPDIR) -type f -name '*.Td' -delete 2>/dev/null
find $(OBJDIR) $(DEPDIR) $(BINDIR) -type d -empty -exec 'rmdir' '-p' {} \; 2>/dev/null
```

**Comment by avdstaaij** [comment]
This is definitely an improvement, but it's not quite perfect yet: if the user sets either `OBJDIR`, `DEPDIR` or `BINDIR` to `.`, this still causes empty directory cleaning in `.`, and it's not very unusual for the user to set `BINDIR` to `.`.

In #5, I have changed this to the code below. See my commits there for the reasons. Note that this still doesn't solve the above issue.
```make
.PHONY: c
c:
	-find . -type f -path './$(OBJDIR)/*.o'  -exec $(RM) {} +
	-find . -type f -path './$(DEPDIR)/*.d'  -exec $(RM) {} +
	-find . -type f -path './$(DEPDIR)/*.Td' -exec $(RM) {} +
	-find $(OBJDIR) $(DEPDIR) -type d -empty -exec 'rmdir' '-p' {} \; 2>/dev/null || true

.PHONY: clean
clean: c
	-$(RM) $(BIN_R)
	-$(RM) $(BIN_D)
	-find $(BINDIR) -type d -empty -exec 'rmdir' '-p' {} \; 2>/dev/null || true
```

**Comment by avdstaaij** [comment]
Since we're not creating subdirectories inside `BINDIR`, it would suffice to remove that with
```bash
if [ -d $(BINDIR) ]; then rmdir --ignore-fail-on-non-empty -p $(BINDIR); fi
```
The same isn't true for object and dependency files, but it's very unlikely for the user to set those to go to `.`

It might save us a lot of headaches if allow the user to set something like `BLDDIR` in which the object and dependency files are placed and then just assume that it is not `.` and recursively clean it. In fact, I believe we could then even hardcode the names `obj`, `dep`, `release` and `debug`, since I don't actually think it is very useful for the user to be able to change these names. If we do that, it would be very safe to clean `$(BLDDIR)/obj` and `$(BLDDIR)/dep` recursively. Do you agree with this?

**Comment by Thyrum** [comment]
The `BLDDIR` idea I agree with. We could even add a check that errors if `BLDDIR==.`. Do watch out when using `--ignore-fail-on-non-empty` though. This doesn't suppress errors but instead allows `rmdir` to delete non-empty directories.

**Comment by avdstaaij** [comment]
> Do watch out when using `--ignore-fail-on-non-empty` though. This doesn't suppress errors but instead allows `rmdir` to delete non-empty directories.

Are you sure? For me it just suppresses errors.

**Comment by Thyrum** [comment]
> > Do watch out when using `--ignore-fail-on-non-empty` though. This doesn't suppress errors but instead allows `rmdir` to delete non-empty directories.
> 
> Are you sure? For me it just suppresses errors.

Turns out the `rmtrash` command I use is implemented incorrectly. I opened an [issue](https://github.com/PhrozenByte/rmtrash/issues/15) for this. Conclusion, we should use `--ignore-fail-on-non-empty`.

**Comment by Thyrum** [comment]
> Since we're not creating subdirectories inside `BINDIR`, it would suffice to remove that with
> 
> ```shell
> if [ -d $(BINDIR) ]; then rmdir --ignore-fail-on-non-empty -p $(BINDIR); fi
> ```

That would work as well yes. Good thinking.

> The same isn't true for object and dependency files, but it's very unlikely for the user to set those to go to `.`
> 
> It might save us a lot of headaches if allow the user to set something like `BLDDIR` in which the object and dependency files are placed and then just assume that it is not `.` and recursively clean it. In fact, I believe we could then even hardcode the names `obj`, `dep`, `release` and `debug`, since I don't actually think it is very useful for the user to be able to change these names. If we do that, it would be very safe to clean `$(BLDDIR)/obj` and `$(BLDDIR)/dep` recursively. Do you agree with this?

Using a `$(BLDDIR)` variable seems sensible. We could even error out when `$(BLDDIR)` is set to `.` with a message like ''_you monster!_'' I'd propose implementing this after merging #5 since we have stalled #5 for long enough and it is not the point of #5.

**Comment by avdstaaij** [comment]
> Using a `$(BLDDIR)` variable seems sensible. We could even error out when `$(BLDDIR)` is set to `.` with a message like ''_you monster!_''

I'm a fan of this :). I did something similar when I integrated testing into a personal Makefile version.

> I'd propose implementing this after merging #5 since we have stalled #5 for long enough and it is not the point of #5.

Agreed. I can clean up #5 soon.
